// <auto-generated />
using System;
using App_VentasCompras.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App_VentasCompras.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("App_VentasCompras.Models.Categoria", b =>
                {
                    b.Property<int>("IDCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDCategoria"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IDCategoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("App_VentasCompras.Models.Persona", b =>
                {
                    b.Property<int>("IDPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDPersona"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IDUbicacion")
                        .HasColumnType("int");

                    b.Property<int>("IDUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NroCelular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IDPersona");

                    b.HasIndex("IDUbicacion")
                        .IsUnique();

                    b.HasIndex("IDUsuario")
                        .IsUnique();

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("App_VentasCompras.Models.Producto", b =>
                {
                    b.Property<int>("IDProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDProducto"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IDCategoria")
                        .HasColumnType("int");

                    b.Property<int>("IDUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IDProducto");

                    b.HasIndex("IDCategoria");

                    b.HasIndex("IDUsuario");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("App_VentasCompras.Models.ProductoVenta", b =>
                {
                    b.Property<int>("IDProductoVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDProductoVenta"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("EstadoProducto")
                        .HasColumnType("int");

                    b.Property<int>("EstadoVenta")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IDProducto")
                        .HasColumnType("int");

                    b.HasKey("IDProductoVenta");

                    b.HasIndex("IDProducto")
                        .IsUnique();

                    b.ToTable("ProductoVentas");
                });

            modelBuilder.Entity("App_VentasCompras.Models.Status", b =>
                {
                    b.Property<int>("IDStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDStatus"));

                    b.Property<int>("IDUsuario")
                        .HasColumnType("int");

                    b.Property<int?>("VentasExitosas")
                        .HasColumnType("int");

                    b.HasKey("IDStatus");

                    b.HasIndex("IDUsuario")
                        .IsUnique();

                    b.ToTable("Status");
                });

            modelBuilder.Entity("App_VentasCompras.Models.Ubicacion", b =>
                {
                    b.Property<int>("IDUbicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDUbicacion"));

                    b.Property<string>("Calle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NroCalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDUbicacion");

                    b.ToTable("Ubicaciones");
                });

            modelBuilder.Entity("App_VentasCompras.Models.Usuario", b =>
                {
                    b.Property<int>("IDUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDUsuario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IDUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("App_VentasCompras.Models.Valoracion", b =>
                {
                    b.Property<int>("IDValoraciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDValoraciones"));

                    b.Property<int?>("Bueno")
                        .HasColumnType("int");

                    b.Property<int>("IDStatus")
                        .HasColumnType("int");

                    b.Property<int?>("Malo")
                        .HasColumnType("int");

                    b.Property<int?>("Regular")
                        .HasColumnType("int");

                    b.HasKey("IDValoraciones");

                    b.HasIndex("IDStatus")
                        .IsUnique();

                    b.ToTable("Valoraciones");
                });

            modelBuilder.Entity("App_VentasCompras.Models.Persona", b =>
                {
                    b.HasOne("App_VentasCompras.Models.Ubicacion", "Ubicacion")
                        .WithOne()
                        .HasForeignKey("App_VentasCompras.Models.Persona", "IDUbicacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App_VentasCompras.Models.Usuario", "Usuario")
                        .WithOne("Persona")
                        .HasForeignKey("App_VentasCompras.Models.Persona", "IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ubicacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("App_VentasCompras.Models.Producto", b =>
                {
                    b.HasOne("App_VentasCompras.Models.Categoria", "Categoria")
                        .WithMany("Producto")
                        .HasForeignKey("IDCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App_VentasCompras.Models.Usuario", "Usuario")
                        .WithMany("Productos")
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("App_VentasCompras.Models.ProductoVenta", b =>
                {
                    b.HasOne("App_VentasCompras.Models.Producto", "Producto")
                        .WithOne("ProductoVenta")
                        .HasForeignKey("App_VentasCompras.Models.ProductoVenta", "IDProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("App_VentasCompras.Models.Status", b =>
                {
                    b.HasOne("App_VentasCompras.Models.Usuario", "Usuario")
                        .WithOne("Status")
                        .HasForeignKey("App_VentasCompras.Models.Status", "IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("App_VentasCompras.Models.Valoracion", b =>
                {
                    b.HasOne("App_VentasCompras.Models.Status", "Status")
                        .WithOne("Valoracion")
                        .HasForeignKey("App_VentasCompras.Models.Valoracion", "IDStatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("App_VentasCompras.Models.Categoria", b =>
                {
                    b.Navigation("Producto");
                });

            modelBuilder.Entity("App_VentasCompras.Models.Producto", b =>
                {
                    b.Navigation("ProductoVenta")
                        .IsRequired();
                });

            modelBuilder.Entity("App_VentasCompras.Models.Status", b =>
                {
                    b.Navigation("Valoracion")
                        .IsRequired();
                });

            modelBuilder.Entity("App_VentasCompras.Models.Usuario", b =>
                {
                    b.Navigation("Persona")
                        .IsRequired();

                    b.Navigation("Productos");

                    b.Navigation("Status");
                });
#pragma warning restore 612, 618
        }
    }
}
